2020-08-06 11:29:10,835 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2020-08-06 11:29:10,835 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\Gebruiker\Desktop\dev\channel_generator\venv\lib\site-packages\instabot\bot\bot.py
2020-08-06 11:29:10,836 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2020-08-06 11:29:11,089 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2020-08-06 11:29:11,270 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2020-08-06 11:29:11,451 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2020-08-06 11:29:11,640 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2020-08-06 11:29:14,268 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2020-08-06 11:29:14,268 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/2440677292/4rg3AuSYOT/", "api_path": "/challenge/2440677292/4rg3AuSYOT/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail", "error_type": "checkpoint_challenge_required"}'
2020-08-06 11:29:14,268 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2020-08-06 11:29:14,268 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2020-08-06 11:29:14,269 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
